name: toolbox_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0